#!/bin/bash
canonical_readlink () {
    # OS X doesn't ship with GNU readlink.
    cd $(dirname $1);
    __filename=$(basename $1);
    if [ -h "$__filename" ]; then
        canonical_readlink $(readlink $__filename$);
    else
        echo "$(pwd -P)";
    fi
}

realdir=$(canonical_readlink $0)

. ${realdir}/uCA-utils.sh

pushd ${realdir} >/dev/null
destroy_file_structure
popd >/dev/null
